name: kadu_ngo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter_native_image: ^0.0.6
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  equatable: ^2.0.2
  video_player: ^2.3.10
  get: ^4.6.1  # for state management and navigation
  flutter_bloc: ^8.1.3
  # firebase_core: ^1.12.0 
  # firebase_auth: ^4.12.1
  # cloud_firestore: ^4.12.2
  flutter_riverpod: ^2.4.5
  go_router: ^12.1.0
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^5.0.1
  rive: ^0.12.2
  google_fonts: ^6.1.0
  connectivity: ^3.0.6
  fluttertoast: ^8.2.2
  auth_code_textfield: ^2.0.7
  formz: ^0.6.1
  auth_service: ^0.0.2
  # amplify_flutter: ^0.5.1
  email_validator: ^2.1.17
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  freezed: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
